### ISSUE TITLE
Error: Unable to add img4 tags to TSS request

### ISSUE THREAD

**Issue by leandroprz** [tihmstar/tsschecker#70]
I'm getting this error on Windows 10 x64:

![Error](http://i.imgur.com/ZkhcMFm.jpg)

Is it relevant for restoring with futurerestore?

**Comment by diggitydogg** [comment]
I too am receiving this error on OSX.

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
This has something to do with commit c7a07b3b88d10ff828f277af4959f9b6afcdff02, which adds support for grabbing blobs without a nonce.

**Comment by barberagianluca** [comment]
> --apnonce NONCE	manually specify APNONCE instead of using random one (not required for saving blobs)
> --sepnonce NONCE	manually specify SEPNONCE instead of using random one (not required for saving blobs)

I'm not sure that nonce is the problem

**Comment by tihmstar** [comment]
fixed

**Comment by Yzord** [comment]
I am still having this issue though

> [TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 10.3.1 build 14E304
[TSSC] opening Buildmanifest for iPhone9,4_10.3.1_14E304
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[Error] [TSSR] ERROR: Unable to add img4 tags to TSS request
Saved shsh blobs!
iOS 10.3.1 14E304 IS signed!

**Comment by leandroprz** [comment]
> I am still having this issue though

v230 fixed it for me.
